name: karing
description: karing

publish_to: none 
version: 1.2.3+857
environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.2
  #icons_plus: 5.0.0
  flutter_emoji: 2.5.1
  emoji_regex: ^0.0.5
  dash_flags: 0.1.1
  #fluentui_system_icons: 1.1.258
  #font_awesome_flutter: 10.8.0
  sentry_flutter: 8.14.2
  #device_info_plus: 11.1.1
  #network_info_plus: 6.1.1
  connectivity_plus: 6.1.4
  package_info_plus: 8.3.0 #sentry_flutter
  build_info: 1.0.2
  build_info_android: 1.0.2
  #platform_device_id: 1.0.1
  class_to_string: 1.0.0
  ffi: 2.1.3
  url_launcher: 6.3.1
  #webview_flutter: 4.10.0
  #webview_win_floating: 2.2.9
  flutter_inappwebview:
    #path: ../../KaringX/flutter_inappwebview/flutter_inappwebview
    git: 
      url: https://github.com/KaringX/flutter_inappwebview.git
      ref: 3a5ead04885537489f3226a04cd0481a90183bbe #v6.2.0-beta.3
      path: flutter_inappwebview
  #flutter_inappwebview: 6.2.0-beta.2
  web_socket_channel: 2.4.0 #flutter_test
  #sqlite3_flutter_libs: 0.5.17
  #sqlite_async: 0.5.2
  path_provider: 2.1.5
  flutter_secure_storage: 9.2.4
  protocol_handler: 0.1.6 #0.2.0 cause windows jam when exit
  #syncfusion_flutter_charts: 23.1.43
  #dart_json_mapper: 2.2.7
  #dart_json_mapper_mobx: 2.0.5
  #json_path: 0.7.4
  json_annotation: 4.9.0
  re_editor: 0.7.0
  re_highlight: 0.0.3
  #mobx: 2.1.3
  #flutter_mobx: 2.0.6+5
  #mobx_triple: 1.1.3+1
  #local_notifier: 0.1.5
  #flutter_modular
  #permission_handler: 11.3.1
  #flutter_easy_permission: 1.1.2
  #processors: 1.0.2
  #combine: 0.5.7-0.1.pre
  #isolate_manager: 4.1.5+1
  #combine: 0.5.7
  launch_at_startup: 0.2.2 #pc only 0.2.2 - 0.3.1 StartupApproved cause reg exceptions
  provider: 6.1.2
  #fpdart: 1.1.0
  zxing2: 0.2.4
  qr_code_scanner_plus: 2.0.10+1
  screen_capturer: 0.2.3 #pc only
  defer_pointer: ^0.0.2
  contextmenu: 3.0.0
  image: 4.5.4
  cached_network_image: 3.4.0
  uuid: 4.4.0 #flutter_test 
  slang: 4.7.3
  slang_flutter: 4.7.0
  watcher: 1.1.2
  string_validator: 1.1.0
  punycode_converter: 0.2.1
  #pay: 1.1.0
  #alipay_kit: 5.0.0
  yaml: 3.1.3
  scrollview_observer: 1.26.0
  after_layout: 1.2.0
  flutter_install_referrer: 2.0.2
  windows_single_instance: 1.0.1 #windows only
  flutter_plugin_android_lifecycle: 2.0.24 #file_picker image_picker
  file_picker: 10.2.0
  image_picker: 1.1.2
  tray_manager: 0.5.0 # pc only
  hotkey_manager: 0.2.3  # pc only
  #accessibility_tools: 2.2.2
  android_package_manager: 0.7.1
  logger: 2.5.0
  tuple: 2.0.2
  crypto: 3.0.6
  cryptography: 2.7.0
  cryptography_flutter: 2.3.2
  open_dir: 0.0.2+1 #pc only
  in_app_review: 2.0.10
  path: 1.9.0 #flutter_test
  characters: 1.3.0 #flutter_test
  win32_registry: 1.1.5 #flutter_test
  csv: 6.0.0
  #home_widget: 0.4.1
  share_plus: 10.1.4 #sentry_flutter
  open_file: 3.5.10 #sentry_flutter
  app_installer: 1.3.1
  #dart_ping: 9.0.1
  #flutter_background_service: 5.0.5
  app_settings: 6.1.1
  #duraspeed_checker: ^0.0.1
  #timezone_to_country: 2.2.0
  #local_auth: 2.2.0
  webdav_client: 1.2.2
  mime: 1.0.4
  http: 1.4.0
  http_parser: 4.0.2
  icloud_storage: 2.2.0 #https://github.com/lollipopkit/flutter_server_box/blob/d94b2a7805891da3e652a9a65cc0c774a2ec6db4/lib/core/utils/sync/icloud.dart#L32
  archive: 4.0.7
  #code_text_field: 1.1.0
  #flutter_speed_dial: 7.0.0
  flutter_inapp_notifications: 1.0.0 
  flutter_local_notifications: 18.0.1
  #awesome_notifications: 0.9.2 
  quick_actions: ^1.1.0
  google_mobile_ads: 5.3.1
  #gdpr_admob: 1.0.2
  #user_messaging_platform: 1.3.0
  convex_bottom_bar: ^3.2.0
  move_to_background: #1.0.2
    #path: ../move_to_background/
    git:
      url: https://github.com/KaringX/move_to_background.git
      ref: 9720fa00946af134caf04b05702230d4329f857f
  country: # 4.1.9
    #path: ../country/country/
    git:
      url: https://github.com/KaringX/country.git
      ref: e744de90f18911a595a486413b535b486fc92219
      path: country
  window_manager: #0.3.7 #pc only
    #path: ../window_manager/packages/
    git:
      url: https://github.com/KaringX/window_manager.git
      ref: f0a01b386c45c4a3513811720e2b5fc765ca45f2
      path: packages/window_manager
  vpn_service:
    path: ../vpn-service/
    #git:
      #url: https://github.com/KaringX/vpn-service.git
      #ref: main

dev_dependencies:
  sentry_dart_plugin: 2.4.1
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter

  flutter_lints: 5.0.0
  ffigen: 18.0.0 # install llvm, https://pub.dev/packages/ffigen,build:dart run ffigen
  #build_runner: 2.4.15
  #json_serializable: 6.9.0 #dart run build_runner build --delete-conflicting-outputs


flutter:
  uses-material-design: true
  assets:
    - assets/zashboard/
    - assets/zashboard/assets/
    - assets/txts/
    - assets/fonts/
    - assets/images/
    - assets/datas/
    - assets/datas/geosite/
    - assets/datas/geoip/
    - assets/datas/acl/
    - assets/datas/preset/

  fonts:
    - family: Emoji # from hiddify
      fonts:
        - asset: assets/fonts/Emoji.ttf
    - family: AntDesign # from icons_plus
      fonts:
        - asset: assets/fonts/AntDesign.ttf

ffigen:
  llvm-path:
    - D:/Program Files/LLVM
    - /usr/lib/llvm-11
    - /usr/local/opt/llvm

#https://www.appicon.co/
flutter_launcher_icons: #flutter pub run flutter_launcher_icons
  android: ic_launcher
  ios: true
  image_path: logo-round.png
  min_sdk_android: 21 # android min sdk min:16, default 21
  image_path_android: logo-round.png
  image_path_ios: logo.png
  remove_alpha_ios: true
  windows:
    generate: false 
    image_path: logo-round.png
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: logo-round-macos.png #macos https://github.com/Yidadaa/ChatGPT-Next-Web/issues/156  1024 -> 854 -> 1024

sentry:
  upload_debug_symbols: false
  upload_source_maps: false
  upload_sources: false
  project:
  org:
  auth_token:
  url:
  wait_for_processing: false
  log_level: error # possible values: trace, debug, info, warn, error
  release:
  web_build_path:
  commits: auto
  ignore_missing: true

parts: #linux flutter_secure_storage
  uet-lms:
    source: .
    plugin: flutter
    #flutter-target: lib/main.dart
    build-packages:
      - libsecret-1-dev
      - libjsoncpp-dev
    stage-packages:
      - libsecret-1-0
      - libjsoncpp-dev
#linux 
#sudo apt-get install libayatana-appindicator3-dev #linux tray_manager
#sudo apt-get install keybinder-3.0 #linux hotkey_manager
#sudo apt-get install libsecret-1-dev
#sudo apt-get install libjsoncpp-dev #flutter_secure_storage

#sudo apt-get install curl
#sudo apt-get install libssl-dev libcurl4-openssl-dev